remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Nick's Incredible Website
description: As my grandma used to say, "Do or do not. There is no try"... or was that Master Yoda?
<img src="{{ 'assets/Optimize Disc.jpg' | relative_url }}" alt="Speaking of buttons...">
